### ISSUE TITLE
editor.getPath is not a function

### ISSUE THREAD

**Issue by lyricat** [dundalek/atom-markdown-mindmap#15]
`/Users/home/.atom/packages/markdown-mindmap/lib/main.coffee:128
Hide Stack Trace
TypeError: editor.getPath is not a function
    at Object.autoOpen (/Users/home/.atom/packages/markdown-mindmap/lib/main.coffee:128:22)
    at /Users/home/.atom/packages/markdown-mindmap/lib/main.coffee:52:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:288:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:437:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:681:19)`

Atom 1.12.8
OSX 10.12.2

**Comment by dundalek** [comment]
This should be now fixed in v0.3.1 update.
