### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by markhuyong** [dundalek/atom-markdown-mindmap#38]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.11.6
**Thrown From**: [markdown-mindmap](https://github.com/dundalek/atom-markdown-mindmap) package 0.4.2

### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At module.js:545

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/markdown-mindmap/lib/markdown-mindmap-view.coffee:4:24)
    at /packages/markdown-mindmap/lib/markdown-mindmap-view.coffee:1:1)
    at /packages/markdown-mindmap/lib/markdown-mindmap-view.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at isMarkdownMindmapView (/packages/markdown-mindmap/lib/main.coffee:11:26)
    at Object.toggle (/packages/markdown-mindmap/lib/main.coffee:105:8)
    at /packages/markdown-mindmap/lib/main.coffee:67:10)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -1:45 settings-view:open (input.hidden-input)
     -0:12.6.0 markdown-mindmap:toggle (div.tool-panel.tree-view)
```

### Non-Core Packages

```
busy-signal 1.4.3 
color-picker 2.3.0 
intentions 1.1.5 
language-scala 1.1.9 
language-swift 0.5.0 
linter 2.2.0 
linter-scalac 1.4.4 
linter-ui-default 1.7.1 
markdown-mindmap 0.4.2 
markdown-preview-enhanced 0.15.6 
merge-conflicts 1.4.5 
minimap 4.29.8 
scala-format 0.1.8 
travis-ci-status 1.3.1 
vim-mode 0.66.0 
Zen 0.18.0 
```

**Comment by markhuyong** [comment]
china has to use mirror:
- [atom设置国内镜像 - CSDN博客](https://blog.csdn.net/lj402159806/article/details/76862981)
