### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by DSigmund** [dundalek/atom-markdown-mindmap#8]
[Enter steps to reproduce below:]
1. strg shift p
2. mindmap, copy html

**Atom Version**: 1.0.0
**System**: FH-ATSP257
**Thrown From**: [markdown-mindmap](https://github.com/dundalek/atom-markdown-mindmap) package, v0.2.4
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\sigmundd\.atom\packages\markdown-mindmap\lib\main.coffee:49

TypeError: undefined is not a function
  at atom-workspace.atom.commands.add.markdown-mindmap:copy-html (C:\Users\sigmundd\.atom\packages\markdown-mindmap\lib\main.coffee:49:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:180:20)

```
### Commands

```
     -2:27.1.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -2:14.6.0 settings-view:uninstall-packages (atom-text-editor.editor.is-focused)
     -1:37.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:36.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:36.6.0 markdown-mindmap:toggle (atom-text-editor.editor)
     -0:31.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:31 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:31 markdown-mindmap:toggle (atom-text-editor.editor)
     -0:30.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:26 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:23.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:23.2.0 markdown-mindmap:copy-html (atom-text-editor.editor)
     -0:08.6.0 command-palette:toggle (div.markdown-mindmap.native-key-bindings...markdown-mindmap-theme-colorful)
     -0:06.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 markdown-mindmap:copy-html (div.markdown-mindmap.native-key-bindings...markdown-mindmap-theme-colorful)
```
### Config

``` json
{
  "core": {
    "projectHome": "\"C:\\Users\\sigmundd\\My Code\\Git01\"",
    "disabledPackages": [
      "achieve-atom"
    ]
  },
  "markdown-mindmap": {
    "theme": "colorful"
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.22
atom-jade, v0.3.0
autoclose-html, v0.21.0
color-picker, v2.0.9
docblockr, v0.7.3
file-icons, v1.6.14
highlight-selected, v0.11.2
language-docker, v1.1.6
line-ending-converter, v1.3.2
linter, v1.11.3
linter-bootlint, v1.0.0
linter-htmlhint, v1.0.2
linter-jshint, v2.0.2
linter-raml, v0.2.2
linter-stylelint, v1.13.0
markdown-mindmap, v0.2.4
minimap, v4.19.0
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.1
package-sync, v1.0.0
perltidy, v2.2.0
pigments, v0.24.1
raml, v0.2.0
remote-sync, v3.5.0
Stylus, v3.0.0
sync-settings, v0.6.0
tabs-to-spaces, v1.0.1

# Dev
No dev packages
```

**Comment by dundalek** [comment]
Fixed in a new release v0.3.0, `Copy to Html` command is now not listed.
